### ISSUE TITLE
Support for later versions of path_provider

### ISSUE THREAD

**Issue by schisms** [GAM3RG33K/flutter_settings_screens#34]
Really enjoying the plugin, and are using it for my settings screen. However, I am encountering a fairly significant problem. Many of my packages are requiring later versions of path_provider. The maximum supported by flutter_settings_screens appears to be 1.4.4, but the latest version of path_provider is 2.0.1. I am having trouble updating plugins because of this. 

Thanks ~~

**Comment by GAM3RG33K** [comment]
Hi, @schisms, thank you for using this library. I am glad you liked it. If you can work with v1.4.4 of path_provider for some time, then I request you to keep using the same. I am planning a few major updates but due to time constraints it is not possible to work on them.
I am planning to update the dependencies & refactroing the internal logic to comply with new flutter norms & dart SDK changes.
At very last I will start migrating to null safe version.

However, If you can't wait for these updates, you can always move a fork of this plugin to your project offline & make changes required for your project. 

Thank you again for using this library.

**Comment by riklarkin** [comment]
Hi @schisms , I created a fork yesterday solely for the purpose of updating the 3 dependencies in the pubspec.yaml file. I needed to do this to avoid version conflicts, you can thus use that version if it helps. Make your pubspec.yaml file like this:

flutter_settings_screens: # Will revert to pub.dev version once they release a null safety update
    git:
      url: https://github.com/riklarkin/flutter_settings_screens

When this version is updated then I'll remove my plugin and go back to using this master one.

**Comment by GAM3RG33K** [comment]
@schisms I have merged the pull request #36 created for updating all the packages & flutter changes to latest versions.
You can check these changes & use the latest master branch checkout if you need.

I'll keep this issue open for some time & close once everthing is verified properly.

**Comment by IanWorthington** [comment]
> @schisms I have merged the pull request #36 created for updating all the packages & flutter changes to latest versions.
> You can check these changes & use the latest master branch checkout if you need.
> 
> I'll keep this issue open for some time & close once everthing is verified properly.

The pubspec.yaml specifies 1.6.8, rather than the latest.  Is that deliberate?

**Comment by GAM3RG33K** [comment]
Yes, This is according to the latest version supported by the last flutter
version in 1.x category.

Support for flutter 2.x will be added in stage 2.

I did this to allow most people to easily migrate to next plugin if there's
any changes required.

I'll be giving the 2.x version update soon.

**Comment by Androz2091** [comment]
Yes, and the package is only using shared_preferences 0.5
is it possible to bump it?

**Comment by GAM3RG33K** [comment]
@Androz2091  Every package is now bumped up in the latest pull request #42 

The same has been released as v0.2.2+1 on pub.dev
