### ISSUE TITLE
Dependency null safety issue with v0.2.2+1

### ISSUE THREAD

**Issue by vladaman** [GAM3RG33K/flutter_settings_screens#44]
I am still getting following error ever after #34 #42 fixes have been merged in v0.2.2+1.
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_settings_screens
 - package:flutter_material_color_picker
```

Using:
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /opt/flutter
    • Framework revision b1395592de (9 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
```

in pubspec.yaml:
```
flutter_settings_screens: ^0.2.2+1
```

see https://github.com/Pyozer/flutter_material_color_picker/issues/26

**Comment by GAM3RG33K** [comment]
Null safety migration #49 merged successfully & published as `v0.3.0-null-safety`. 

Though it is a prerelease version right now, to find & fix some quick bugs if any.
Soon it will be a stable one.

Note: Since the actual plugin for material color picker has not migrated to null safety, I have included a local copy of the latest plugin version with null-safety changes. Once the actual plugin is migrated, I'll make sure to move to that plugin ASAP.
