### ISSUE TITLE
Does SliderSettingsTile support int values?

### ISSUE THREAD

**Issue by msthoma** [GAM3RG33K/flutter_settings_screens#47]
I'm using SliderSettingsTile for a slider for a range of integers. The documentation mentions _"This widget supports double and integer types of values which should be put in the preference"_, but I haven't found how to actually force the type to be integer. I looked through the source and previous issues for hints, but didn't find an answer (issue #2 is the only mention I found that is related). Is there a way to do this?

I'm already handling this by making sure I'm converting from double to int whenever I'm retrieving the value for the setting, so this is not a huge issue. I was just wondering if I was missing something obvious. Thanks!

**Comment by GAM3RG33K** [comment]
It seems that the updates in Slider settings are incosistant with the documentation at this point.

This raises an important question, how important it is to support integer values while the base widget used for this setting only supports `double` only. Reference: [https://api.flutter.dev/flutter/material/Slider/max.html](https://api.flutter.dev/flutter/material/Slider/max.html)

What should be the way forward? 
1. adding support to `int` by handling conversions internally
2. follow the conventional type that has enough support to manipulate values as needed & update the documentation accordingly.

I'd appreciate your help in resolving this issue in general. I know it won't be a huge task to do either of them, but in first case it will become plugin's responsibliity to handle conversion which may run into bugs due to lossy conversions from `double` to `int`.

**Comment by GAM3RG33K** [comment]
In the latest commit, this issue is resolved.
The slider widget will only use & provide `double` values. However, developer will have a choice to print the value as integer using `decimalPrecision` property of the widget.

**Comment by msthoma** [comment]
Great solution - there is no need to add support for `int`s, especially since the base widget does not support them. Thanks!
