### ISSUE TITLE
RadioModalSettingsTile

### ISSUE THREAD

**Issue by domizilver** [GAM3RG33K/flutter_settings_screens#6]
the selected value from RadioModalSettingsTile is not saving in the subtitle. it keep resetting after changing page

**Comment by domizilver** [comment]
also im a bit confuse on setting and loading the shared preferences, can you include that in example.dart? tq

**Comment by GAM3RG33K** [comment]
I'll be looking into this issue, shortly.

Also, as A quick info, you can use following to load the settings from the preference library.
```
Settings.init(cacheProvider: _customCacheProvider);
```

**Note**: If you don't pass the `cacheProvider` parameter, it'll by default use `SharedPreferenceCacheProvider` that comes with the library.

I would recommend checking the code for example app. I am sure it will resolve all your doubts.

**Comment by domizilver** [comment]
im working on the exampleapp. both hive and sp dont save value when closing (for example the light theme).

**Comment by GAM3RG33K** [comment]
If you are referring to the `Light Theme` switch in the example app, then it is not supposed to be saved in preference, since the switch is not part of the settings page. It is just a simple switch.

I want to improve the example app in some time. You are welcome to help me improve it.

**Comment by domizilver** [comment]
oh i see. sorry im super new to this whole coding thing :'( . btw do u know how to retrieve the stored key (from settingspage) to the main page? for example showing a text ``` Wifi is On ``` on main page. i tried to implement this:
```Settings.getValue<T>(key-wifi, defaultValue); ```
in main page initstate() but no success

**Comment by GAM3RG33K** [comment]
Make sure that, 
```
Settings.init(cacheProvider: _customCacheProvider);
```

is called before you try to access the preference values.

I would call this method before `runApp()` method in `main.dart` file. It allows me to access the settings anywhere in the app.

**Comment by domizilver** [comment]
i have all of that, but where do i put "Settings.getValue<T>(key-wifi, defaultValue); "

**Comment by GAM3RG33K** [comment]
Treat this method as a getter for your required value.
For example:
```
final bool isWifiEnabled = Settings.getValue<bool>(key-wifi, false);
```

then use  `isWifiEnabled` where you want.

**Comment by domizilver** [comment]
still not working :(
the _**key-wifi**_ gives an error "undefined name", if i use **_'key-wifi'_** i got red screen error

**Comment by GAM3RG33K** [comment]
There are two problems here:

- key-wifi gives an error "undefined name"
  Because it is not a variable that is defined in the scope of the file, you can create one to resolve this:
  ```
  String key_wifi = 'key_wifi';
  ```

- use 'key-wifi' i got red screen error
  Because everything outside a class or a method is initialized first, so, even though you use 'key_wifi' as settings key, `Settings` itself is not initialized until the `main` method is run...

Following is my suggestions:
 1. Create a global string `key_wifi` as I described above. 
 2. Do not keep the settings/preference as global, just fetch the value when needed.


FYI, 
I will delete this issue later, if possible. As it is not a good place to discuss unrelated issues other than the bugs in plugin. 

You can mail directly to me for any more details or help anytime, I'll try to reply as soon as possivle..

**Comment by domizilver** [comment]
thank you so much for all this man. i have a lot to learn.
